server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://43.139.93.181:3306/t?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: G3xfGgW4
  # redis配置
  redis:
    # redis地址
#    host: 81.70.196.209
    # 端口
#    port: 6379
#    password: M2orw3h1
    redisson:
      # https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter参照官方文档 使用file
      file: classpath:redisson/redisson-single.yml
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


